const SUPABASE_URL = 'https://mkagzmamqddzrojielop.supabase.co';
const SUPABASE_KEY = 'sb_publishable_NxX8YjEWydRur8H4bAqe1g_3dwaGE8g';
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

const tabellen = {
  'Zahlen': {
    '0 bis 9': [['de','0','fr','zéro'],['de','1','fr','un'],['de','2','fr','deux'],['de','3','fr','trois'],['de','4','fr','quatre'],['de','5','fr','cinq'],['de','6','fr','six'],['de','7','fr','sept'],['de','8','fr','huit'],['de','9','fr','neuf']],
    '10 bis 19': [['de','10','fr','dix'],['de','11','fr','onze'],['de','12','fr','douze'],['de','13','fr','treize'],['de','14','fr','quatorze'],['de','15','fr','quinze'],['de','16','fr','seize'],['de','17','fr','dix-sept'],['de','18','fr','dix-huit'],['de','19','fr','dix-neuf']]
  },
  'Grundlagen': {
    'Wochentage': [['de','Montag','fr','lundi'],['de','Dienstag','fr','mardi'],['de','Mittwoch','fr','mercredi'],['de','Donnerstag','fr','jeudi'],['de','Freitag','fr','vendredi'],['de','Samstag','fr','samedi'],['de','Sonntag','fr','dimanche']]
  }
};

let currentUser = null;
let selectedLessons = new Set();
let trainingData = [];
let trainingIndex = 0;
let trainingWrong = [];
let currentView = 'trainer';
let repeatMode = false;
let savedFirstAttempt = false;
let statsFilter = { from: '', to: '' };
const el = id => document.getElementById(id);
function calculateGrade(percent) { if (percent >= 92) return 1; if (percent >= 81) return 2; if (percent >= 67) return 3; if (percent >= 50) return 4; if (percent >= 30) return 5; return 6; }
function getGradeText(grade) { return {1:'Sehr gut',2:'Gut',3:'Befriedigend',4:'Ausreichend',5:'Mangelhaft',6:'Ungenügend'}[grade] || '-'; }
function withinRange(dateStr) { const d = new Date(dateStr); if (statsFilter.from) { const from = new Date(statsFilter.from); from.setHours(0,0,0,0); if (d < from) return false; } if (statsFilter.to) { const to = new Date(statsFilter.to); to.setHours(23,59,59,999); if (d > to) return false; } return true; }
function setView(view) { currentView = view; el('trainerSection').classList.toggle('hidden', view !== 'trainer'); el('statsSection').classList.toggle('hidden', view !== 'stats'); el('navTrainer').classList.toggle('active', view === 'trainer'); el('navStats').classList.toggle('active', view === 'stats'); el('pageTitle').textContent = view === 'trainer' ? 'Trainer' : 'Statistik'; el('pageSubtitle').textContent = view === 'trainer' ? 'Erstes Ergebnis speichert automatisch. Wiederholungen werden nicht gespeichert.' : 'Werte aus allen gespeicherten Erstversuchen.'; if (view === 'stats') loadStats(); }
async function login() { const email = el('email').value; const password = el('password').value; const { data, error } = await supabaseClient.auth.signInWithPassword({ email, password }); if (error) { el('loginError').textContent = error.message; el('loginError').classList.remove('hidden'); return; } currentUser = data.user; el('loginView').classList.add('hidden'); el('appView').classList.remove('hidden'); await loadProfile(); renderLessons(); await loadStats(); updateTrainerSummary(); setView('trainer'); }
async function loadProfile() { const { data } = await supabaseClient.from('profiles').select('*').eq('id', currentUser.id).single(); if (!data) return; const parts = []; if (data.can_learn_en) parts.push('Englisch aktiv'); if (data.can_learn_fr) parts.push('Französisch aktiv'); el('languageInfo').textContent = parts.length ? parts.join(' · ') : 'Keine Sprache freigeschaltet.'; }
async function loadStats() { if (!currentUser) return; const { data, error } = await supabaseClient.from('lesson_results').select('*').eq('user_id', currentUser.id).order('created_at', { ascending: false }); if (error) { el('lessonStats').innerHTML = `<div class="error-box">Statistik konnte nicht geladen werden: ${error.message}</div>`; return; } const rows = (data || []).filter(r => withinRange(r.created_at)); el('statSessions').textContent = rows.length; el('statLearned').textContent = rows.reduce((s, r) => s + Number(r.total_words || 0), 0); el('statWrong').textContent = rows.reduce((s, r) => s + Number(r.wrong_words || 0), 0); el('statCorrect').textContent = rows.reduce((s, r) => s + Number(r.correct_words || 0), 0); const totalWords = rows.reduce((s, r) => s + Number(r.total_words || 0), 0); const correctWords = rows.reduce((s, r) => s + Number(r.correct_words || 0), 0); const percent = totalWords ? Math.round((correctWords / totalWords) * 100) : 0; el('statPercent').textContent = `${percent}%`; el('statGrade').textContent = rows.length ? (rows.reduce((s, r) => s + Number(r.grade || 0), 0) / rows.length).toFixed(1) : '-'; const grouped = new Map(); rows.forEach(r => { const k = `${r.language}|${r.lesson_group}|${r.sublesson}`; if (!grouped.has(k)) grouped.set(k, { ...r, sessions: 0, total_words: 0, wrong_words: 0, correct_words: 0, gradeSum: 0 }); const g = grouped.get(k); g.sessions += 1; g.total_words += Number(r.total_words || 0); g.wrong_words += Number(r.wrong_words || 0); g.correct_words += Number(r.correct_words || 0); g.gradeSum += Number(r.grade || 0); }); const items = Array.from(grouped.values()); if (!items.length) { el('lessonStats').innerHTML = '<div class="error-empty">Für diesen Zeitraum wurden keine Trainingsdaten gefunden.</div>'; return; } el('lessonStats').innerHTML = items.map(item => { const p = item.total_words ? Math.round((item.correct_words / item.total_words) * 100) : 0; const avg = (item.gradeSum / item.sessions).toFixed(1); return `<div class="list-item"><div><h5>${item.lesson_group} · ${item.sublesson}</h5><p>${item.language.toUpperCase()} · Sessions: ${item.sessions} · Wörter: ${item.total_words}</p></div><div style="display:flex;gap:10px;flex-wrap:wrap;justify-content:flex-end;"><span class="chip ${item.language === 'en' ? 'en' : 'fr'}">${item.language.toUpperCase()}</span><span class="chip ok">${p}% richtig</span><span class="chip">Ø-Note ${avg}</span></div></div>`; }).join(''); }
function updateTrainerSummary() { if (!currentUser) return; const now = new Date(); const start = new Date(now); start.setDate(start.getDate() - 6); start.setHours(0,0,0,0); supabaseClient.from('lesson_results').select('*').eq('user_id', currentUser.id).order('created_at', { ascending: false }).then(({ data, error }) => { const box = el('trainerSummary'); if (error || !box) return; const rows = (data || []).filter(r => new Date(r.created_at) >= start); const words = rows.reduce((s, r) => s + Number(r.total_words || 0), 0); const correct = rows.reduce((s, r) => s + Number(r.correct_words || 0), 0); const wrong = rows.reduce((s, r) => s + Number(r.wrong_words || 0), 0); const percent = words ? Math.round((correct / words) * 100) : 0; const grade = rows.length ? calculateGrade(percent) : '-'; box.innerHTML = `<div class="stats-grid"><div class="stat-box"><span>7 Tage</span><strong>${rows.length}</strong></div><div class="stat-box"><span>Wörter</span><strong>${words}</strong></div><div class="stat-box"><span>Richtig</span><strong>${correct}</strong></div><div class="stat-box"><span>Falsch</span><strong>${wrong}</strong></div><div class="stat-box"><span>Quote</span><strong>${percent}%</strong></div><div class="stat-box"><span>Ø-Note</span><strong>${grade}</strong></div></div>`; }); }
function renderLessons() { const container = el('lessonList'); container.innerHTML = ''; Object.keys(tabellen).forEach(group => { const groupBox = document.createElement('div'); groupBox.className = 'group'; const titleCount = Object.keys(tabellen[group]).length; groupBox.innerHTML = `<div class="group-head"><div class="group-left"><h5>${group}</h5><p>${titleCount} Unterlektionen</p></div><div class="pill">${Object.values(tabellen[group]).flat().length} Wörter</div></div><div class="lessons">${Object.keys(tabellen[group]).map(sub => { const count = tabellen[group][sub].length; const key = `${group}|${sub}`; return `<div class="lesson ${selectedLessons.has(key) ? 'active' : ''}" data-key="${key}"><div><strong>${sub}</strong><small>${count} Wörter</small></div><div class="check">+</div></div>`; }).join('')}</div>`; container.appendChild(groupBox); }); container.querySelectorAll('.lesson').forEach(lesson => { lesson.onclick = () => { const key = lesson.dataset.key; if (selectedLessons.has(key)) selectedLessons.delete(key); else selectedLessons.add(key); renderLessons(); }; }); el('selectionInfo').textContent = `${selectedLessons.size} Unterlektionen ausgewählt`; updateTrainerSummary(); }
function showTrainingQuestion() { if (trainingIndex >= trainingData.length) return showTrainingResult(); const vocab = trainingData[trainingIndex]; el('trainingQuestion').textContent = vocab[1]; el('trainingAnswer').value = ''; el('trainingAnswer').focus(); el('trainingProgress').style.width = `${(trainingIndex / trainingData.length) * 100}%`; }
function checkAnswer() { const userInput = el('trainingAnswer').value.trim(); const answer = userInput.toLowerCase(); const correct = trainingData[trainingIndex][3].toLowerCase(); if (answer !== correct) trainingWrong.push({ vocab: trainingData[trainingIndex], userInput }); trainingIndex++; showTrainingQuestion(); }
function showTrainingResult() { el('trainingArea').classList.add('hidden'); el('trainingResult').classList.remove('hidden'); const total = trainingData.length; const correct = total - trainingWrong.length; const wrong = trainingWrong.length; const percent = total ? Math.round((correct / total) * 100) : 0; const grade = calculateGrade(percent); el('resultCorrect').textContent = correct; el('resultWrong').textContent = wrong; el('resultTotal').textContent = total; el('resultGrade').textContent = grade; el('resultGradeText').textContent = getGradeText(grade); const errorsContainer = el('resultErrors'); if (trainingWrong.length === 0) { errorsContainer.innerHTML = '<div class="error-empty">🎉 Perfekt! Alle Vokabeln richtig!</div>'; el('repeatWrongBtn').classList.add('hidden'); } else { el('repeatWrongBtn').classList.remove('hidden'); errorsContainer.innerHTML = trainingWrong.map((entry, i) => `<div class="error-card"><div class="error-header"><span>Fehler #${i + 1}</span></div><div class="error-rows"><div class="error-row"><div><label>Deutsch</label><div>${entry.vocab[1]}</div></div><div><label>Deine Eingabe</label><div class="error-your">${entry.userInput || 'Leer'}</div></div></div><div class="error-row" style="border-top:1px solid #fecaca;padding-top:12px;"><div style="grid-column:1 / -1;"><label>Richtige Lösung</label><div class="error-correct">${entry.vocab[3]}</div></div></div></div></div>`).join(''); } if (!repeatMode && !savedFirstAttempt) autoSaveResult(total, correct, wrong, percent, grade); }
async function autoSaveResult(total, correct, wrong, percent, grade) { const result = { user_id: currentUser.id, language: 'fr', lesson_group: 'Demo-Gruppe', sublesson: 'Demo-Unterlektion', total_words: total, correct_words: correct, wrong_words: wrong, percent_score: percent, grade: grade }; const { error } = await supabaseClient.from('lesson_results').insert([result]); if (!error) { savedFirstAttempt = true; await loadStats(); updateTrainerSummary(); } }
async function startTraining() { if (selectedLessons.size === 0) return alert('Wähle mindestens eine Unterlektion!'); trainingData = []; selectedLessons.forEach(key => { const [group, sub] = key.split('|'); trainingData = trainingData.concat(tabellen[group][sub]); }); trainingData = trainingData.sort(() => Math.random() - 0.5); trainingIndex = 0; trainingWrong = []; repeatMode = false; savedFirstAttempt = false; el('lessonList').style.display = 'none'; el('startTrainingBtn').style.display = 'none'; el('trainingArea').classList.remove('hidden'); el('trainingResult').classList.add('hidden'); showTrainingQuestion(); }
document.addEventListener('DOMContentLoaded', () => { el('loginBtn').onclick = login; el('password').addEventListener('keydown', e => { if (e.key === 'Enter') login(); }); el('email').addEventListener('keydown', e => { if (e.key === 'Enter') login(); }); el('navTrainer').onclick = () => setView('trainer'); el('navStats').onclick = () => setView('stats'); el('refreshBtn').onclick = () => currentView === 'stats' ? loadStats() : renderLessons(); el('refreshStatsBtn').onclick = () => loadStats(); el('applyStatsFilterBtn').onclick = () => { statsFilter.from = el('statsFrom').value; statsFilter.to = el('statsTo').value; loadStats(); }; el('clearStatsFilterBtn').onclick = () => { statsFilter = { from: '', to: '' }; el('statsFrom').value = ''; el('statsTo').value = ''; loadStats(); }; el('startTrainingBtn').onclick = startTraining; el('checkAnswerBtn').onclick = checkAnswer; el('skipBtn').onclick = () => { trainingIndex++; showTrainingQuestion(); }; el('trainingAnswer').onkeydown = e => { if (e.key === 'Enter') checkAnswer(); }; el('repeatWrongBtn').onclick = () => { if (trainingWrong.length === 0) return; repeatMode = true; trainingData = trainingWrong.map(x => x.vocab).sort(() => Math.random() - 0.5); trainingIndex = 0; trainingWrong = []; el('trainingResult').classList.add('hidden'); el('trainingArea').classList.remove('hidden'); showTrainingQuestion(); }; el('newTrainingBtn').onclick = () => { selectedLessons.clear(); renderLessons(); el('lessonList').style.display = 'block'; el('startTrainingBtn').style.display = 'block'; el('trainingResult').classList.add('hidden'); el('trainingArea').classList.add('hidden'); el('selectionInfo').textContent = '0 Unterlektionen ausgewählt'; trainingData = []; trainingIndex = 0; trainingWrong = []; repeatMode = false; savedFirstAttempt = false; updateTrainerSummary(); }; el('logoutBtn').onclick = async () => { await supabaseClient.auth.signOut(); location.reload(); }; });
